/*
 * Licensed to Jecstar Innovation under one or more contributor
 * license agreements. Jecstar Innovation licenses this file to you
 * under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied. See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 03:55:56 PM CEST 
//


package com.jecstar.etm.processor.ibmmq.event;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for BitstreamData complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="BitstreamData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bitstream">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="encoding" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}encodingType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BitstreamData", propOrder = {
        "bitstream"
})
public class BitstreamData {

    @XmlElement(required = true)
    private BitstreamData.Bitstream bitstream;

    /**
     * Gets the value of the bitstream property.
     *
     * @return possible object is
     * {@link BitstreamData.Bitstream }
     */
    public BitstreamData.Bitstream getBitstream() {
        return bitstream;
    }

    /**
     * Sets the value of the bitstream property.
     *
     * @param value allowed object is
     *              {@link BitstreamData.Bitstream }
     */
    public void setBitstream(BitstreamData.Bitstream value) {
        this.bitstream = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="encoding" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}encodingType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Bitstream {

        @XmlValue
        String value;
        @XmlAttribute(name = "encoding", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
        EncodingType encoding;

        /**
         * Gets the value of the value property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the encoding property.
         *
         * @return possible object is
         * {@link EncodingType }
         */
        public EncodingType getEncoding() {
            return encoding;
        }

        /**
         * Sets the value of the encoding property.
         *
         * @param value allowed object is
         *              {@link EncodingType }
         */
        public void setEncoding(EncodingType value) {
            this.encoding = value;
        }

    }

}
