== Changelog & upgrade

=== Version 3.0.0
* Migration to Elasticsearch 6.1.x.
* Support for Java 9.
* Parsers can use metadata as source for parsing.
* Added a ''Copy value'' parser.
* Make the number of update threads to Elasticsearch configurable.
* Support for bulk events in JMS & MQ processor.

==== Upgrade from version 2.4.0 to 3.0.0
. Make sure you have a backup of all Elasticsearch data!
. Download and uncompress Elasticsearch 5.6.x to a new directory.
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Copy the 'config/elasticsearch.yml' file from your current Elasticsearch nodes to your new ones.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Download and uncompress {etm} 3.0.0 to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the file 'config/etm.yml' from your old {etm} installation to the new one. Remove the option 'nrOfListeners' under the ibmMq chapter. This option must be replaced with the 'minNrOfListeners' and 'maxNrOfListeners' options. See the <<IBM MQ section in etm.yml>> for more information.
. Start a single {etm} node and wait for the data migration to complete.
. Start all other {etm} nodes.

=== Version 2.4.0
* Fixed Terms and Significant Terms autocompletion fields in Graphs page.
* Upgrade to Elasticsearch 5.6.x.
* Removed \_missing_ query parameter. It should be replaced with NOT \_exists_
* Added JMS processor.
* Fixed LDAP Authentication bug.
* Option to download all users to a csv or excel sheet.

==== Upgrade from version 2.x to 2.4.0
. Make sure you have a backup of all Elasticsearch data!
. Download and uncompress Elasticsearch 5.6.x to a new directory.
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Copy the 'config/elasticsearch.yml' file from your current Elasticsearch nodes to your new ones.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Dowload and uncompress {etm} 2.4.0 to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the file 'config/etm.yml' from your old {etm} installation to the new one. Remove the options 'maxConcurrentRequests', 'maxQueuedRequests' & 'sessionTimeout' under the http chapter. These parameters may now be provided for the GUI and REST processor separately. See the <<Http section in etm.yml>> for more information.
. Start your {etm} nodes.

=== Version 2.3.0
* Support for x-pack secured Elasticsearch clusters.
* Upgrade to Elasticsearch 5.5.x.
* Separate rate limiting on GUI and REST processor. 

==== Upgrade from version 2.x to 2.3.0
. Make sure you have a backup of all Elasticsearch data!
. Download and uncompress Elasticsearch 5.5.x to a new directory. 
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Copy the 'config/elasticsearch.yml' file from your current Elasticsearch nodes to your new ones.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Dowload and uncompress {etm} 2.3.0 to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the file 'config/etm.yml' from your old {etm} installation to the new one. Remove the options 'maxConcurrentRequests', 'maxQueuedRequests' & 'sessionTimeout' under the http chapter. These parameters may now be provided for the GUI and REST processor separately. See the <<Http section in etm.yml>> for more information.
. Start your {etm} nodes.

=== Version 2.2.0 
* Upgrade to Elasicsearch 5.4.x.
* Support for basic authentication on rest processor.
* Added audit logs to audit the usage of {etm}.
* Configurable ringbuffer wait strategy.
* Automatic date interval determination in graphs.
* Custom y-axis format in graphs.
* Automatic installation of free license.
* Allow subtree scope in LDAP user authentication.
* Add a write policy to endpoint configurations alowing fields to be overwritten.