== Changelog

=== Version 3.2.0
* [ETM-43] Start script always starts 'tail' functionality.
* [ETM-44] Set empty id's to 'null' in processors.
* [ETM-45] Add http status code field.

=== Version 3.1.1
* [ETM-33] Fix upgrade documentation on website.
* [ETM-34] Autocomplete not working in IE.
* [ETM-35] Download transaction to file.
* [ETM-36] Option to show ETM logs from command line.
* [ETM-37] No results when sorting on non-existing field.
* [ETM-38] Apply the same filterquery only one time.
* [ETM-39] env connectAddresses not working in Docker.
* [ETM-40] Default search templates not working anymore.
* [ETM-41] Graphs not updating in IE.
* [ETM-42] Add first reader time to event details screen.

=== Version 3.1.0
* LDAP Synchronization of users.
* Fixed bug in removing account with user settings access.
* Added features requested by Achmea.
* Allow the <<XSLT parser>> as transforming parser on an Endpoint.
* Add metadata to endpoint handler.
* Moved reading_endpoint_handlers and writing_endpoint_handler to endpoint_handlers.

=== Version 3.0.2
* Fixed a bug that failed migrations from 2.x to 3.0.x because of metric fields containing NaN.
* Changed spinner in top right corner to a pulsing Jecstar logo in the top left corner.

=== Version 3.0.1
* Added a Regular expression parser
* Option to change payload before it is store in Elasticsearch

=== Version 3.0.0
* Added the link:https://kafka.apache.org/[Kafka] processor.
* Sophisticated access control for every single page.
* Migration to Elasticsearch 6.2.x.
* Support for Java 9.
* Parsers can use metadata as source for parsing.
* Added a ''Copy value'' parser.
* Make the number of update threads to Elasticsearch configurable.
* Support for bulk events in JMS & MQ processor.

=== Version 2.4.0
* Fixed Terms and Significant Terms autocompletion fields in Graphs page.
* Upgrade to Elasticsearch 5.6.x.
* Removed \_missing_ query parameter. It should be replaced with NOT \_exists_
* Added JMS processor.
* Fixed LDAP Authentication bug.
* Option to download all users to a csv or excel sheet.

=== Version 2.3.0
* Support for x-pack secured Elasticsearch clusters.
* Upgrade to Elasticsearch 5.5.x.
* Separate rate limiting on GUI and REST processor. 

=== Version 2.2.0
* Upgrade to Elasicsearch 5.4.x.
* Support for basic authentication on rest processor.
* Added audit logs to audit the usage of {etm}.
* Configurable ringbuffer wait strategy.
* Automatic date interval determination in graphs.
* Custom y-axis format in graphs.
* Automatic installation of free license.
* Allow subtree scope in LDAP user authentication.
* Add a write policy to endpoint configurations alowing fields to be overwritten.

== Upgrades
{etm} is maintaining a semantic versioning strategy. Given a version number MAJOR.MINOR.PATCH, increment the:

* MAJOR version when {etm} contains incompatible API changes,
* MINOR version when {etm} adds functionality in a backwards-compatible manner, and
* PATCH version when {etm} makes backwards-compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

=== Upgrades within the same MAJOR version.

. Make sure you have a backup of all Elasticsearch data!
. Download and uncompress the required Elasticsearch version to a new directory.
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Copy the 'config/elasticsearch.yml' file from your current Elasticsearch nodes to your new ones.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Dowload and uncompress {etm} to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the file 'config/etm.yml' from your old {etm} installation to the new one.
. Check if any of the <<Version specific changes>> applies to your situation.
. Start your {etm} nodes.

==== Version specific changes
Sometimes your {etm} configuration needs additional changes before it can be upgraded. This section describes these changes necessary before upgrading.

===== Upgrade from versions before 2.3.0 to 2.3.x or higher
. Remove the options 'maxConcurrentRequests', 'maxQueuedRequests' & 'sessionTimeout' under the http chapter in the file 'config/etm.yml'. These parameters may now be provided for the GUI and REST processor separately. See the <<Http section in etm.yml>> for more information.

=== Upgrade from version 2.4.0 to 3.x
. Your data will be converted during the upgrade so as always make sure you have a backup of all Elasticsearch data!
. Download and uncompress Elasticsearch 6.2.x to a new directory.
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Copy the 'config/elasticsearch.yml' file from your current Elasticsearch nodes to your new ones.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Download and uncompress {etm} 3.0.x to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the file 'config/etm.yml' from your old {etm} installation to the new one.
.. Remove the option 'nrOfListeners' under the ibmMq chapter. This option must be replaced with the 'minNrOfListeners' and 'maxNrOfListeners' options. See the <<IBM MQ section in etm.yml>> for more information.
.. Changes configuration elasticsearch.connectAddresses to a list. For example
[source,yaml,subs=attributes+]
    ----
    elasticsearch:
      connectAddresses:
      - "127.0.0.1:9300"
      - "server-2:9300"
    ----
.. If you want to play save, disable all processors. This will prevent events to be processed in the case your migrated somehow failed.
. Start a single {etm} node in console mode and wait for the data migration to complete. Login to {etm} and validate the migration.
. Enable all required processors when disabled in a previous step and start the node.
. Start all other {etm} nodes.

