== Changelog
=== Version 4.0.0

* [ETM-18] Allow/Deny server certificates.
* [ETM-23] Remove all api references to event type.
* [ETM-103] Change gui to themekita.
* [ETM-105] Option to export and import graphs + signals.
* [ETM-106] Upgrade to elasticsearch 7.x
* [ETM-107] Add a quicksearch bar.
* [ETM-108] Replace endpoint configuration with import profiles.
* [ETM-109] Endpoints tab should show all endpoints in chain.
* [ETM-110] Ldap groups never reloaded.
* [ETM-113] Email recipients disappeared after saving signal.
* [ETM-114] java.lang.IllegalArgumentException during migration of version 3.5.2.
* [ETM-115] Show application instance in event chain tab.
* [ETM-116] Show stacktrace in console and tail commands.
* [ETM-117] Legend not correct in Pie charts.

=== Version 3.5.2

* [ETM-112] Note that auto scaling to maxNrOfListeners only works on local queues.
* [ETM-111] ETM stops reading messages after 5 minutes.

=== Version 3.5.1
* [ETM-100] Log to console when quiet = false.
* [ETM-101] Calendar buttons in signals & graphs not working in IE.
* [ETM-102] Memory leak in LruCache.

=== Version 3.5.0
* [ETM-95] Add api key to user for for authorisation on rest processor.
* [ETM-96] Wrong timestamp when using flatpickr.
* [ETM-97] License reload may fail when system under stress.
* [ETM-98] Option to configure the context root of the gui and rest processor.
* [ETM-99] Order By and Path not correctly displayed when showing graph data.

=== Version 3.4.1
* [ETM-86] Dashboard and signal datasources not refreshed in groups settings screen.
* [ETM-87] Dashboard context menu hidden when insufficient height in column.
* [ETM-88] Option to disable a Signal.
* [ETM-89] Autocomplete not working in graphs and signals.
* [ETM-90] Graphs not working in IE.
* [ETM-91] Click on search result might show an empty page.
* [ETM-92] Wrong name in pipeline path selector when referencing other pipelines.
* [ETM-93] Missing thousands separator in Number graphs.
* [ETM-94] Number graphs not refreshing on dashboard.

=== Version 3.4.0
* [ETM-17] Migrate etm-domain to public repository.
* [ETM-51] Migrate to Elasticsearch REST client.
* [ETM-76] Advanced graphs.
* [ETM-77] Fix "Accessing variable [ctx] via [params.ctx] from within a update script is deprecated in favor of directly accessing [ctx]".
* [ETM-78] Unable to show event chain when response time is sub millisecond.
* [ETM-79] Payload correlated event is visible with role "Read without payload".
* [ETM-80] Upgrade to Elasticsearch 6.6.
* [ETM-84] Remove WADL exposure.
* [ETM-85] Migrate docker image to AdoptOpenJdk 11.

=== Version 3.3.0
* [ETM-57] Sorting not working on all fields.
* [ETM-58] Query on dashboards should default to all attributes.
* [ETM-60] Expose and authorize all datasources in dashboard/signal.
* [ETM-61] Add health check page.
* [ETM-62] Move jvm options to separate file.
* [ETM-63] Use user timezone in event chain details.
* [ETM-64] Use button to open calendar in search screen.
* [ETM-65] Add startdate and enddate fields on graphs.
* [ETM-66] Make endpoint cache size configurable.
* [ETM-67] Option to set timestamp fields in search result table as start or end date for the query.
* [ETM-68] Sorting on metric in term aggregator not working when sub aggregator is present.
* [ETM-69] Migrate to Elasticsearch 6.4.
* [ETM-70] Allow search time filter on all time fields.
* [ETM-71] Add role that allows to see all but payload from event.
* [ETM-72] Log downloads in audit log.
* [ETM-73] Add SNMP notifier.
* [ETM-75] Drop nvd3 and migrate all charts to Highcharts.

=== Version 3.2.0
* [ETM-14] Add signals.
* [ETM-43] Start script always starts 'tail' functionality.
* [ETM-44] Set empty id's to 'null' in processors.
* [ETM-45] Add http status code field.
* [ETM-46] Group visualizations not visible in some cases.
* [ETM-47] LDAP groups of user not visible in users screen.
* [ETM-49] Option to use secure cookies.
* [ETM-50] Label required fields italic.
* [ETM-52] Index of current day unwritable after migration from 2.4 to 3.1.1.
* [ETM-53] Parser keeps attached to endpoint when removed.
* [ETM-54] Payload not visible when invalid payload_format is set.
* [ETM-55] XsltExpressionParser is not thread safe.

=== Version 3.1.1
* [ETM-33] Fix upgrade documentation on website.
* [ETM-34] Autocomplete not working in IE.
* [ETM-35] Download transaction to file.
* [ETM-36] Option to show ETM logs from command line.
* [ETM-37] No results when sorting on non-existing field.
* [ETM-38] Apply the same filterquery only one time.
* [ETM-39] env connectAddresses not working in Docker.
* [ETM-40] Default search templates not working anymore.
* [ETM-41] Graphs not updating in IE.
* [ETM-42] Add first reader time to event details screen.

=== Version 3.1.0
* LDAP Synchronization of users.
* Fixed bug in removing account with user settings access.
* Added features requested by Achmea.
* Allow the <<XSLT parser>> as transforming parser on an Endpoint.
* Add metadata to endpoint handler.
* Moved reading_endpoint_handlers and writing_endpoint_handler to endpoint_handlers.

=== Version 3.0.2
* Fixed a bug that failed migrations from 2.x to 3.0.x because of metric fields containing NaN.
* Changed spinner in top right corner to a pulsing Jecstar logo in the top left corner.

=== Version 3.0.1
* Added a Regular expression parser
* Option to change payload before it is store in Elasticsearch

=== Version 3.0.0
* Added the link:https://kafka.apache.org/[Kafka] processor.
* Sophisticated access control for every single page.
* Migration to Elasticsearch 6.2.x.
* Support for Java 9.
* Parsers can use metadata as source for parsing.
* Added a ''Copy value'' parser.
* Make the number of update threads to Elasticsearch configurable.
* Support for bulk events in JMS & MQ processor.

== Upgrades
{etm} is maintaining a semantic versioning strategy. Given a version number MAJOR.MINOR.PATCH, increment the:

* MAJOR version when {etm} contains incompatible API changes,
* MINOR version when {etm} adds functionality in a backwards-compatible manner, and
* PATCH version when {etm} makes backwards-compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

=== Upgrades within the same MAJOR version.

. Make sure you have a backup of all Elasticsearch data!
. Download and uncompress the required Elasticsearch version to a new directory. See the <<Support matrix>> for the version you should run.
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Copy the 'config/elasticsearch.yml' file from your current Elasticsearch nodes to your new ones.
. Merge changes from the 'config/jvm.options' and 'config/log4j2.properties' files in your current Elasticsearch nodes to your new ones. Note that merging is only recommended when you have made changes to those files. When you've not changed anything in those files it is recommended to leave them untouched in your new Elasticsearch installation.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Download and uncompress {etm} to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the 'config/etm.yml' & 'config/jvm.options' files from your old {etm} installation to the new one. Note that older versions of {etm} might not have a 'config/jvm.options' file.
. Check if any of the <<Version specific changes>> applies to your situation.
. Start your {etm} nodes.

==== Version specific changes
Sometimes your {etm} configuration needs additional changes before it can be upgraded. This section describes these changes necessary before upgrading.

===== Upgrade from versions before 3.5.0 to 3.5.x or higher
. Remove the option 'restProcessorLoginRequired' in the http chapter in the file 'config/etm.yml'. This option is replaced by the api key functionality.

===== Upgrade from versions before 3.4.0 to 3.4.x or higher
. Change the 'connectAddresses' in the elasticsearch chapter from the Elasticsearch transport address to the Elasticsearch http address.
. Remove the options 'sslEnabled', 'sslKeyLocation', 'sslCertificateLocation' & 'sslCertificateAuthoritiesLocation' in the elasticsearch chapter in the file 'config/etm.yml'. These options are replaced by 'sslTrustStoreLocation' and 'sslTrustStorePassword' which can hold a jks key store.

=== Upgrade from version 3.5.0 to 4.x
. Your data will be converted during the upgrade so as always make sure you have a backup of all Elasticsearch data!
. Make sure you have a non-ldap (local) admin account! {etm} requires the import of server certificates starting with release 4.x so you wont be able to login using an LDAP account configured on an LDAP server connected over TLS.
. {etm} requires Java 11. Download and install Java 11 when necessary.
. Download and uncompress Elasticsearch 7.x to a new directory.
. Stop all {etm} nodes.
. Stop your current Elasticsearch nodes.
. Merge changes from the 'config/jvm.options' and 'config/log4j2.properties' files in your current Elasticsearch nodes to your new ones. Note that merging is only recommended when you have made changes to those files. When you've not changed anything in those files it is recommended to leave them untouched in your new Elasticsearch installation.
. If your Elasticsearch data resides in the same directory as your Elasticsearch installation make sure you copy the data to the new Elasticsearch installation.
. Start your new Elasticsearch nodes and wait for the message ''Cluster health status changed from [RED] to [GREEN]'' to appear.
. Download and uncompress {etm} 4.x to a new directory.
. Copy all files under 'lib/ext/' from your old {etm} installation to the new one.
. Copy the 'config/etm.yml' & 'config/jvm.options' files from your old {etm} installation to the new one.
.. If you want to play save, disable all processors in the etm.yml. This will prevent events to be processed in the case your migrated somehow failed.
. Start a single {etm} node in console mode and wait for the data migration to complete. Login to {etm} and validate the migration.
.. <<Certificate settings,Import>> your LDAP and/or SMTP certificates used to setup a secure connection.
. Enable all required processors when disabled in a previous step and restart the node.
. Start all other {etm} nodes.
