== Processing events
{etm} needs to be feeded with events to do its magic. This can be done with 2 main transport methods: 

. Sending events to the rest processor
. Sending events to an IBM message queue or topic that is read by the IBM MQ processor.

Depending on your current infrastructure and expected load you can pick any of these options. When guaranteed delivery and processing of your events is a requirement than sending the event to a message queue is the best option for you. On the other hand the rest processor doesn't need any changes to your infrastructure but if the processor is down for maintenance no events will be processed, and the applications sending events will likely drop the events that can't be delivered.

Performance wise there is no advantage in picking one specific processor. {etm} is capable of processing ~50.000 log events per second on a single instance. Of course the more information you provide in your event, the more time it will take to process the event. Also memory and disk speed can influence the throughput of events in a relatively high way.

=== Rest processor

=== IBM MQ processor

