== Setup {etm}
This section explains in detail the steps to download, configure and run an {etm} installation. Because {etm} is a pure Java application it should be able to run on any machine with a proper Java runtime installed. At a minimum a link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java 8] runtime should be availabe. It is recommended to install JDK from Oracle's site, but {etm} might run with other JDK suppliers as well.

For the storage of the events {etm} relies on an link:http://www.elastic.co/downloads[Elasticsearch 5.0] or compatible cluster. Both the Java runtime, and Elasticsearch cluster are not part of {etm} and need to be installed, configured and managed separately.

=== Installation with .tgz
The .tgz archive for {etm} can be downloaded and installed as follow:

[source,bash,subs=attributes+]
----
wget http://www.jecstar.com/downloads/etm-{project-version}.tgz
wget http://www.jecstar.com/downloads/etm-{project-version}.tgz.sha512
cat etm-{project-version}.tgz.sha512 | sha512sum -c ## <1>
tar -zxvf etm-{project-version}.tgz
cd etm-{project-version}/bin
./etm ## <2>
----
<1> Checks the sha512 hash of the downloaded file. If not ok, this command will fail.
<2> This command does not actually start {etm} but shows the options that are available with the etm script.

=== Installation with .zip
The .zip archive for {etm} can be downloaded and installed as follow:

[source,bash,subs=attributes+]
----
wget http://www.jecstar.com/downloads/etm-{project-version}.zip
wget http://www.jecstar.com/downloads/etm-{project-version}.zip.sha512
cat etm-{project-version}.tgz.sha512 | sha512sum -c ## <1>
unzip etm-{project-version}.tgz 
cd etm-{project-version}/bin
./etm ## <2>
----
<1> Checks the sha512 hash of the downloaded file. If not ok, this command will fail.
<2> This command does not actually start {etm} but shows the options that are available with the etm script.

=== Configuring {etm}
Once {etm} is downloaded and installed we are ready to configure the node properly. Part of the configuration is managed in a configuration file, but most of the options are available in the gui. We will first explain the configuration that is done in the configuration file, and finally run and configure {etm} with the gui.

[[section_node-configuration]]
==== Node configuration
Each {etm} Node has its own configuration file. The file can be found at <INSTALL_DIR>/config/etm.yml. When playing around with {etm} the defaults will be sufficient, but when you configure a production instance you probably need to tune some configuration options. The configuration file is split into 5 main sections: general, elasticsearch, http, ibm mq and logging.

===== General configuration in etm.yml
General configuration options have no indentation in the etm.yml file. The following options are available:

.General configuration options
[options="header"]
|=======================
|Name|Default value|Description
|bindingAddress|0.0.0.0|The interface adres to bind {etm} to.
|clusterName|Enterprise Telemetry Monitor|The name of the {etm} cluster. When running multiple {etm} clusters it is recommended to give them a separate name.
|instanceName|Node_1|The name of the Node. When running multiple nodes in a cluster, it is recommended to give them a separate name.
|======================= 

All other configuration sections are identified with the name of the section without indentation. Configration options in that section have an indentation of 2 spaces.

===== Elasticsearch section in etm.yml
The ''elasticsearch'' section contains all options that are necessary to connect to an Elasticsearch cluster:

.Elasticsearch configuration options
[options="header"]
|=======================
|Name|Default value|Description
|clusterName|elasticsearch|The name of the Elasticsearch cluster to connect to.
|connectAddresses|127.0.0.1:9300|A comma separated list of Elasticsearch nodes to connect to. When high availablilty is a demand of your production environment you should provide at least 2 addresses.
|=======================

===== Http section in etm.yml
The ''http'' section contains all options that are necessary to start the gui and rest processor:

.Http configuration options
[options="header"]
|=======================
|Name|Default value|Description
|guiEnabled|true|Should the GUI be enabled? Set this value to false if you don't want users to use the gui on this node. The gui is bound to the ''/gui'' context on your server and can be accessed by browsing to \http://<bindingAddress>:<httpPort>/gui
|restProcessorEnabled|true|Should the rest processor be enabled? Set this value to false if you don't want this node to act as a processor that can process events with a REST api. The REST api is bound to the ''/rest/processor/'' context and can be access from \http://<bindingAddress>:<httpPort>/rest/processor/ 
|httpPort|8080|The port to bind the http listener to.
|httpsPort|8443|The port to bind the secure https listener to. The listener will not start unless the sslKeystore is properly configured.
|maxConcurrentRequests|100|The maximum number of request that can be processed in parallel at any given moment. This is the number of request to the gui and rest processor combined. If the number exceeds the maximum, the requests will be queued.
|maxQueuedRequests|100|The maximum number of requests that can be queued. If a request needs to be queued and the maximum number of queued requests exceeds this maximum the request will be rejected.
|sslProtocol|TLSv1.2|The ssl protocol that needs to be used on the secure https listener. The allowed values are depending on your Java installation, but unless you have specific demands the default will be sufficient secure.
|sslKeystoreLocation||The location of you ssl keystore. The keystore contains your public/private key pair to identify your server.
|sslKeystorePassword||The password of the ssl keystore. When provided, make sure the configuration is will not be readable for everyone but allow only the etm process can read it.
|sslKeystoreType|PKCS12|The ssl keystore type.
|sslKeystoreLocation||The location of you ssl truststore. The trust store contains certificates of machines that are allowed to connect to this Node. When not provided, everybody is allowed to access this Node although a a username and password are still necessary to login.
|sslKeystorePassword||The password of the ssl truststore. When provided, make sure the configuration is will not be readable for everyone but allow only the etm process can read it.
|sslKeystoreType|JSK|The ssl truststore type.
|=======================

===== IBM MQ section in etm.yml
The ''ibmMq'' section contains all options that are necessary to process {etm} events from a IBM MQ queue or topic. To make use of this feature you need to copy a file named ''com.ibm.mq.allclient.jar'' from your MQ installation to the <INSTALL_DIR>/lib directory. Due to the MQ license Jecstar is not allowed to provide this specific library with {etm}.

.IBM MQ configuration options
[options="header"]
|=======================
|Name|Default value|Description
|enabled|false|Should the IBM MQ processor be enabled? Set this value to true to process messages from defined IBM MQ queue's and/or topics.
|=======================

==== IBM Integration Bus integration
