package com.jecstar.etm.gui;

import static org.junit.Assert.assertTrue;

import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

import org.junit.Test;

import com.jecstar.etm.domain.HttpTelemetryEvent;
import com.jecstar.etm.domain.HttpTelemetryEvent.HttpEventType;
import com.jecstar.etm.domain.LogTelemetryEvent;
import com.jecstar.etm.domain.PayloadFormat;
import com.jecstar.etm.domain.builders.ApplicationBuilder;
import com.jecstar.etm.domain.builders.EndpointBuilder;
import com.jecstar.etm.domain.builders.EndpointHandlerBuilder;
import com.jecstar.etm.domain.builders.HttpTelemetryEventBuilder;
import com.jecstar.etm.domain.builders.LogTelemetryEventBuilder;
import com.jecstar.etm.domain.writers.TelemetryEventWriter;
import com.jecstar.etm.domain.writers.json.HttpTelemetryEventWriterJsonImpl;
import com.jecstar.etm.domain.writers.json.LogTelemetryEventWriterJsonImpl;

/**
 * Class testing the event overview.
 * 
 * @author Mark Holster
 */
public class EventOverviewTest extends AbstractIntegrationTest {
	
	private final TelemetryEventWriter<String, HttpTelemetryEvent> httpEventWriter = new HttpTelemetryEventWriterJsonImpl(); 
	private final TelemetryEventWriter<String, LogTelemetryEvent> logEventWriter = new LogTelemetryEventWriterJsonImpl(); 
	
	@Test
	public void testEventOverview() {
		final String eventId = UUID.randomUUID().toString();
		final ApplicationBuilder guiApplication = new ApplicationBuilder()
													.setName("Gui application")
													.setVersion("1.0.0");
		final String guiApplicationTransactionId = UUID.randomUUID().toString();
		
		ZonedDateTime timestamp = ZonedDateTime.now();
		// A user requests the shopping card page from our public http site.
		HttpTelemetryEvent httpTelemetryEvent = new HttpTelemetryEventBuilder()
			.setId(eventId)
			.setPayload("GET http://www.my-company.com/shopping-card.html")
			.setPayloadFormat(PayloadFormat.HTML)
			.setHttpEventType(HttpEventType.GET)
			.addMetadata("User-Agent", "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0")
			.addMetadata("Pragma", "no-cache")
			.addOrMergeEndpoint(new EndpointBuilder()
									.setName("/shopping-card.html")
									.addReadingEndpointHandler(new EndpointHandlerBuilder()
																	.setHandlingTime(timestamp)
																	.setTransactionId(guiApplicationTransactionId)
																	.setApplication(guiApplication)
															  )
								)
			.build();
		assertTrue(sendEventToEtm("http", this.httpEventWriter.write(httpTelemetryEvent)));
		
		// Add some logging generated by our gui app.
		timestamp = timestamp.plus(15, ChronoUnit.MILLIS);
		assertTrue(sendEventToEtm("log", this.logEventWriter.write(new LogTelemetryEventBuilder()
				.setPayload("User is requesting his/her shopping card.")
				.setPayloadFormat(PayloadFormat.TEXT)
				.setLogLevel("DEBUG")
				.addOrMergeEndpoint(new EndpointBuilder()
							.setName("com.my-company.gui.Httphandler.handleRequest(Httphandler.java:59)")
							.setWritingEndpointHandler(new EndpointHandlerBuilder()
										.setApplication(guiApplication)
										.setTransactionId(guiApplicationTransactionId)
										.setHandlingTime(timestamp)
									)
						)
				.build())));
		
		timestamp = timestamp.plus(8, ChronoUnit.MILLIS);
		assertTrue(sendEventToEtm("log", this.logEventWriter.write(new LogTelemetryEventBuilder()
				.setPayload("Requesting shoppping card over MQ.")
				.setPayloadFormat(PayloadFormat.TEXT)
				.setLogLevel("DEBUG")
				.addOrMergeEndpoint(new EndpointBuilder()
							.setName("com.my-company.gui.MqRequestor.requestShoppingCar(MqRequestor.java:352)")
							.setWritingEndpointHandler(new EndpointHandlerBuilder()
										.setApplication(guiApplication)
										.setTransactionId(guiApplicationTransactionId)
										.setHandlingTime(timestamp)
									)
						)
				.build())));
		
		
	}

}
